@startuml
|Usuario|
start
:Iniciar sesión;
:Seleccionar productos;
|Sistema de Carrito|
if (¿Producto disponible en Inventario?) then (sí)
  :Agregar producto al carrito;
else (no)
  :Mostrar mensaje "Producto no disponible";
  stop
endif

:Confirmar carrito de compras;
|Usuario|
:Ingresar detalles de pago;
|Sistema de Carrito|
:Generar factura;
:Actualizar inventario;
|Usuario|
:Finalizar compra;
stop
@enduml
